name: FastAPI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests (Postgres service)
      env:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb"
      run: |
        pip install pytest pytest-asyncio
        pytest -v

    - name: Check app starts
      env:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb"
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 >/dev/null 2>&1 &
        # wait until server is ready
        for i in {1..30}; do
          curl -fsS http://127.0.0.1:8000/Countries && break
          sleep 1
        done
        curl -f http://127.0.0.1:8000/Countries
